### ISSUE TITLE
Crash on startup with Mac

### ISSUE THREAD

**Issue by jeremyherbert** [JesusFreke/fusion_idea_addin#1]
Hi,

On startup I am receiving this error: 

```
2020-08-08 18:30:16,373 - CRITICAL - Error occurred while starting the ssdp server.
Traceback (most recent call last):
  File "/Users/jeremy/Library/Application Support/Autodesk/Autodesk Fusion 360/API/AddIns/fusion_idea_addin/fusion_idea_addin.py", line 188, in run_ssdpv4_server
    with SSDPV4Server(self._http_server.server_port) as server:
  File "/Users/jeremy/Library/Application Support/Autodesk/Autodesk Fusion 360/API/AddIns/fusion_idea_addin/fusion_idea_addin.py", line 561, in __init__
    super().__init__(("", 1900), SSDPRequestHandler)
  File "/Users/jeremy/Library/Application Support/Autodesk/webdeploy/production/d384168111c5561ef465b7d90b82fad51eb05636/Autodesk Fusion 360.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/Users/jeremy/Library/Application Support/Autodesk/Autodesk Fusion 360/API/AddIns/fusion_idea_addin/fusion_idea_addin.py", line 564, in server_bind
    super().server_bind()
  File "/Users/jeremy/Library/Application Support/Autodesk/webdeploy/production/d384168111c5561ef465b7d90b82fad51eb05636/Autodesk Fusion 360.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
```

netstat:
```
$ netstat -vatn | grep 1900
udp46      0      0  *.1900                 *.*                                786896   9216  62814      0 0x0000 0x00000004
```

Can't run anything via pycharm, it gives the following message:
```
Public key hash: F93552CFE1C6A07E748BE736BA257F74A94326CD
Server stopped.
Encountered error while attempting to connect to Fusion.
```

Pycharm does however find the right process ID for fusion.

**Comment by Woit** [comment]
any news here?

**Comment by JesusFreke** [comment]
I think ideally someone will need to take on maintenance for Mac-specific issues like this. I have no Mac hardware, and basically no Mac experience. Trying to run Mac in a VM to reproduce and troubleshoot issues like this is... not how I want to spend my time :)

But if someone wants to investigate, I'm happy to accept pull requests and provide pointers/debugging help/etc.
